<a href="https://colab.research.google.com/github/lauratcc18/IAMINTIC/blob/main/1_ANOVA_seleccion_caract_filtro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selección de Características
## Método de filtrado estadístico - univariado
Usaremos el dataset de Diabetes de Kaggle que busca predecir a partir de algunas variables de diagnóstico, si un paciente tiene diabetes.

Descargarlo de https://www.kaggle.com/datasets/mathchi/diabetes-data-set

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

### 1. Importar librerías y dataset
Montamos el drive de google donde tenemos almacenado el archivo de diabetes. Esta acción solicita que se conecte a su cuenta de drive.

<u> Si ya tiene montado el drive, no es necesario ejecutar esta sección.</u>


In [ ]:
from google.colab import drive
drive.mount ('/content/gdrive')

Mounted at /content/gdrive


Importamos las librerías a utilizar:
- Pandas para leer los datos del archivo csv en un DataFrame
- Numpy para manejo arreglos y de opciones de impresión
- Sklearn para las funciones de selección de características

In [ ]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

Antes de leer el csv, declaramos la ruta completa del archivo y los titulos de cada columna.

<u>Nota: Asegúrese de quitar en el archivo la primera línea con los títulos de las columnas.</u>

In [ ]:
ruta = '/content/diabetes.csv'
titulos = ['preg', 'gluc', 'bloodP', 'skin', 'insulin', 'IMC', 'pedi', 'edad', 'salida']
dataframe = read_csv(ruta, names=titulos)
dataframe.head()

preg  gluc  bloodP  skin  insulin   IMC   pedi  edad  salida
0     6   148      72    35        0  33.6  0.627    50       1
1     1    85      66    29        0  26.6  0.351    31       0
2     8   183      64     0        0  23.3  0.672    32       1
3     1    89      66    23       94  28.1  0.167    21       0
4     0   137      40    35      168  43.1  2.288    33       1

In [ ]:
dataframe.shape

(768, 9)

### 2. Dividir los datos en variables de entrada (X) y salida (Y)
Las 8 primeras columnas contienen las variables numéricas de diagnóstico y la última contiene el indicador de clase que se desea predecir, donde un 1 representa que el paciente si es diabético.

In [ ]:
array = dataframe.values
X = array[:,0:8]  # Arreglo de entradas todas las filas
Y = array[:,8]   #Arreglo de salidas
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

<B>Observe los datos y su caracterízación (cantidad de filas y de columnas).</B>
<!-- Puede usar las funciones print o display o el método shape

display(X)
X.shape

-->

In [ ]:
# Escriba su código aqui

type(X)

numpy.ndarray

In [ ]:
display(X)

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
X.shape

(768, 8)

### 3. Aplicar el algoritmo de filtrado para selección de características
Dos de los algoritomos que ofrece sklearn para filtrado de variables son:
- SelectKBest, que selecciona las top-k variables.
- SelectPercentile, que selecciona las variables con el top percentile.

Antes de filtrar las variables, se les debe calcular las estadísticas, aplicando el aloritmo apropiado según el tipo de datos de las variables de entrada y salida. Entre los algoritmos estadísticos que incluye la librería están:
- Coeficiente de correlación de Pearson: f_regression()
- ANOVA: f_classif()
- Chi cuadrado: chi2()
- Información mutua: mutual_info_classif() y mutual_info_regression()
- Kendall: kendalltau()
- Rango de correlación de Spearman: spearmanr()

En el ejemplo tenemos variables numéricas de entrada y un objetivo categórico, por lo que podemos utilizar el algoritmo ANOVA con una selección de los 4 mejores atributos (k).

In [ ]:
# SELECCION DE VARIABLES QUE MAS INFLUYEN PARA LA SACAR LA VARIABLE RESULTADO

# Define la función o estadística de selección de características
#Entrada numeroca y salida categorica... funciona muy bien ANova
#Se puede dividir en set de entrenamiento y de prueba
#se ajusta el modelo de acuerdo al algoritmo y luego transformar los datos

test = SelectKBest(score_func=f_classif, k=4)  # SelectKBest ..  se selecciona con f_classif para ahcer ANOVA

# Aplica la selección de características, identificando y ajsutando los parámetros del modelo. Dado que es un algoritmo supervisado, el método fit recibe la variable objetivo
#Ajustar el modelo segun las slaidas Y
fit = test.fit(X, Y)

# Mostrar los puntajes obtenidos por cada variable al filtrar las características, con 3 dígitos de precisión (cuando aplique)
#imprime los puntajes que le dio a los parametros

set_printoptions(precision=3)
print("Puntos por variable:\n",titulos[0:8],'\n',fit.scores_, '\n')

# Aplica los parámetros aprendidos con fit() y transforma los datos de entrada (reduce X al número de características seleccionadas)
#primero se hace fit y luego se transform
features = fit.transform(X)

# Muestra un resumen con las características seleccionadas
print ("Valores de las variables seleccionadas:\n",features[0:10,:])


Puntos por variable:
 ['preg', 'gluc', 'bloodP', 'skin', 'insulin', 'IMC', 'pedi', 'edad'] 
 [ 39.67  213.162   3.257   4.304  13.281  71.772  23.871  46.141] 

Valores de las variables seleccionadas:
 [[  6.  148.   33.6  50. ]
 [  1.   85.   26.6  31. ]
 [  8.  183.   23.3  32. ]
 [  1.   89.   28.1  21. ]
 [  0.  137.   43.1  33. ]
 [  5.  116.   25.6  30. ]
 [  3.   78.   31.   26. ]
 [ 10.  115.   35.3  29. ]
 [  2.  197.   30.5  53. ]
 [  8.  125.    0.   54. ]]


Al relacionar los puntos por cada variable con las características impresas se observa cuales fueron las 4 características escogidas (las que tienen los mayores puntajes).

<B>¿Qué características se seleccionaron?</B>

In [ ]:
#SE SELECCIONAN LAS 4 DE MAYOR VALOR
#preg', 'gluc', 'bloodP', 'skin', 'insulin', 'IMC', 'pedi', 'edad']
 #[ 39.67  213.162   3.257   4.304  13.281  71.772  23.871  46.141]

 # gloc
 # IMC
 # Edad
 # preg